[package]
name = "raid-notifier"
version = "0.1.0"
authors = ["Agustin Carrasco <asermax@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
notify-rust = "3"
